import { jsPDF } from 'jspdf';
import type { AnalysisResult } from '@/types';
import { getRiskTheme } from './risk';

function formatDate(): string {
  return new Date().toLocaleString(undefined, {
    dateStyle: 'long',
    timeStyle: 'short',
  });
}

/**
 * Generate and trigger download of a PDF report for an analysis.
 * Layout tuned for a clean, readable one-page document.
 */
export function downloadReport(message: string, result: AnalysisResult): void {
  const theme = getRiskTheme(result.riskLevel);
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Header band
  doc.setFillColor(9, 9, 11);
  doc.rect(0, 0, pageWidth, 70, 'F');
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 4, 70, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('ScamShield AI', margin, 36);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(160, 160, 170);
  doc.text('Scam & Phishing Detection Report', margin, 54);
  doc.setFontSize(9);
  doc.text(formatDate(), pageWidth - margin, 54, { align: 'right' });

  y = 100;

  // Risk badge
  const badgeHex = theme.hex;
  doc.setDrawColor(badgeHex);
  doc.setFillColor(badgeHex);
  doc.roundedRect(margin, y - 18, 150, 28, 6, 6, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text(result.riskLevel.toUpperCase(), margin + 75, y, { align: 'center' });

  doc.setTextColor(15, 15, 20);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(32);
  doc.text(`${result.riskScore}%`, pageWidth - margin, y + 4, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 130);
  doc.text('Risk Score', pageWidth - margin, y + 20, { align: 'right' });

  y += 40;
  line(`Scam Category: ${result.scamCategory || 'Unknown'}`);
  line(`Message Type:  ${result.messageType || 'Unknown'}`);
  line(`Confidence:    ${result.confidence || 'N/A'}`);
  y += 8;

  sectionTitle('Summary');
  paragraph(result.summary || 'No summary available.');
  y += 6;

  sectionTitle('Detailed Explanation');
  paragraph(result.explanation || 'No explanation available.');
  y += 6;

  sectionTitle('Red Flags');
  list(result.redFlags);
  y += 6;

  sectionTitle('Psychological Tactics');
  list(result.psychologicalTactics);
  y += 6;

  sectionTitle('Recommended Actions');
  list(result.recommendedActions);
  y += 6;

  sectionTitle('Plain-English Rewrite');
  paragraph(result.rewrite || 'No rewrite available.');
  y += 8;

  sectionTitle('Analyzed Message');
  paragraph(message);

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 28;
  doc.setDrawColor(220, 220, 225);
  doc.line(margin, footerY - 8, pageWidth - margin, footerY - 8);
  doc.setFontSize(8);
  doc.setTextColor(140, 140, 150);
  doc.text(
    'Generated by ScamShield AI — this report is an automated estimate and does not constitute legal or professional advice.',
    pageWidth / 2,
    footerY,
    { align: 'center' },
  );

  doc.save(`scamshield-report-${Date.now()}.pdf`);

  function sectionTitle(title: string) {
    ensure(24);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(37, 99, 235);
    doc.text(title, margin, y);
    y += 16;
  }

  function paragraph(text: string) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 60);
    const lines = doc.splitTextToSize(text, contentWidth) as string[];
    for (const line of lines) {
      ensure(14);
      doc.text(line, margin, y);
      y += 14;
    }
  }

  function list(items: string[]) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 60);
    if (!items.length) {
      ensure(14);
      doc.text('—', margin, y);
      y += 14;
      return;
    }
    for (const item of items) {
      const wrapped = doc.splitTextToSize(`•  ${item}`, contentWidth - 12) as string[];
      for (let i = 0; i < wrapped.length; i++) {
        ensure(14);
        doc.text(wrapped[i], margin + (i === 0 ? 0 : 12), y);
        y += 14;
      }
    }
  }

  function line(text: string) {
    ensure(16);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 70);
    doc.text(text, margin, y);
    y += 16;
  }

  function ensure(needed: number) {
    if (y + needed > doc.internal.pageSize.getHeight() - 40) {
      doc.addPage();
      y = margin;
    }
  }
}

export function buildShareText(message: string, result: AnalysisResult): string {
  const theme = getRiskTheme(result.riskLevel);
  return [
    'ScamShield AI — Analysis Report',
    `Risk: ${result.riskLevel.toUpperCase()} (${result.riskScore}%)`,
    `Category: ${result.scamCategory}`,
    '',
    `Summary: ${result.summary}`,
    '',
    `Red flags: ${result.redFlags.slice(0, 4).join('; ')}`,
    '',
    `Generated ${formatDate()}`,
  ].join('\n');
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch {
    /* fall through to legacy path */
  }
  try {
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.style.position = 'fixed';
    textarea.style.opacity = '0';
    document.body.appendChild(textarea);
    textarea.select();
    const ok = document.execCommand('copy');
    document.body.removeChild(textarea);
    return ok;
  } catch {
    return false;
  }
}
